package learning.proxy;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import net.sf.cglib.proxy.Enhancer;
import proxy.DefaultHello;
import proxy.LogMethodStartInterceptorCglib;

public class ProxyTest {
    @Test 
    public void testSomeLibraryMethod() {
        LogMethodStartInterceptorCglib methodIntercepter = new LogMethodStartInterceptorCglib();
        Enhancer enhancer = new Enhancer();
        enhancer.setSuperclass(DefaultHello.class);
        enhancer.setCallback(methodIntercepter);
        
        DefaultHello helloCglibProxy = (DefaultHello) enhancer.create();
        helloCglibProxy.sayHello("Cglib Proxy");
    }
}
